# Site
name: "Ventspace"
title: "Promit's Ventspace"
description: "Life, the Universe, and Software"
meta_description: "Promit's Ventspace"
logo: 'assets/images/Promit1024.png'
favicon: 'assets/images/Promit256.png'
baseurl: /
# google_analytics: 'UA-46278016-1'
# disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  promit:
    name: Promit
    display_name: Promit
    #gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: promit@promit.dev
    web: promit.dev
    twitter: https://twitter.com/promit_roy
    description: "Promit"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true